- name: "Run tasks locally"
  hosts: localhost
  tasks:

  - name: Set secrets directory
    set_fact:
      orc8r_secrets: /Users/shubham/myfiles/git/ansible-localhost/secrets

  - name: Set Magma Orc8r domain
    set_fact:
      orc8r_domain: "magma.local"

  - name: Create Orchestrator secrets directory
    file:
      path: "{{ orc8r_secrets }}"
      state: directory

  - name: Generate an OpenSSL private key with a different size (2048 bits)
    community.crypto.openssl_privatekey:
      path: "{{ orc8r_secrets }}/rootCA.key"
      size: 2048

  - name: Generate an OpenSSL Certificate Signing Request
    community.crypto.openssl_csr:
      path: "{{ orc8r_secrets }}/rootCA.csr"
      privatekey_path: "{{ orc8r_secrets }}/rootCA.key"
      country_name: US
      common_name: rootca.{{ orc8r_domain }}

  - name: Generate a Self Signed OpenSSL certificate
    community.crypto.x509_certificate:
      path: "{{ orc8r_secrets }}/rootCA.pem"
      privatekey_path: "{{ orc8r_secrets }}/rootCA.key"
      csr_path: "{{ orc8r_secrets }}/rootCA.csr"
      provider: selfsigned
