---
- name: "Run tasks locally"
  hosts: localhost
  tasks:

  - name: Get latest helm version
    uri:
      url: https://api.github.com/repos/helm/helm/tags
    register: latest_helm_version

  - name: Set helm version
    set_fact:
      helm_version: "{{ latest_helm_version.json[0].name }}"

  - name: Latest helm version
    debug:
      msg:
        - "{{ helm_version }}"
