---
- name: "Run tasks locally"
  hosts: localhost
  tasks:

  - name: "just execute a ls -lrt command"
    shell: "ls -lrt"
    register: "output"

  - debug:
      var: output.stdout_lines

  - name: Distribution
    debug: msg="{{ ansible_distribution }}"

  - name: Distribution version
    debug: msg="{{ ansible_distribution_version}}"

  - name: Distribution major version
    debug: msg="{{ ansible_distribution_major_version }}"
